### ISSUE TITLE
Change Z to Space (0x20)

### ISSUE THREAD

**Issue by tsxkasa** [nopeAnon/Automated-HoloCure-Fishing#2]
z key doesn't work, change to space instead, go from z to space, also very buggy on d and a

**Comment by zackszackz** [comment]
it's work? idk why but i always fail in chain 2.. something was wrong, not responsive or too fast.. do you have any solution for this?

**Comment by tsxkasa** [comment]
I don’t really know how to fix but from what I observed, A and D keys are working fine, just not responsive(idk if the timing is off or what), but the space, up and down is working really fine, I also fixed from z to space and it works(the a and d is still off), i assume mss might work better against tracking these thing but i might be wrong.

**Comment by zackszackz** [comment]
i tried to change z to space, awsd to tfgh .. and still not work.. maybe the author can give us the solution

**Comment by tsxkasa** [comment]
bind a new key called space then put value to 0x20 then change enter to the var name then you should be set

**Comment by nopeAnon** [comment]
> i tried to change z to space, awsd to tfgh .. and still not work.. maybe the author can give us the solution

I have changed it to space, since it works regardless of keybindings. If you want to customize the keybindings, please change the lines [10-14](https://github.com/nopeAnon/Automated-HoloCure-Fishing/blob/64e3730b61d99e349a71a61b989a31758298254f/holocure_fishing.py#L10-L14) to your desired key bind. Please use only small letters and check the `buttons` variable for possible key binds.



> it's work? idk why but i always fail in chain 2.. something was wrong, not responsive or too fast.. do you have any solution for this?

Please open a new issue for a different problem. But that is weird. Can you tell me more about it on a new issue? Are you playing in windowed mode at 1280x720? Did you move the window? Did the note miss? Which notes did miss?

**Comment by zackszackz** [comment]
i tried but, i think the problem was in A and D keys.. it's runnin, but somehow the game did't respond to the command

**Comment by tsxkasa** [comment]
the A and D key is running but not working in most of the case, but the rest works fine., I’m on 1280x720 without moving the windows.
